<h1>Comparison operations</h1>



In [13]:
import torch
#returns a dtype torch.bool
torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2])

tensor([ True, False, False])

In [14]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

<h2>Basic comparison operations</h2>
=, < , >, <=, >=

In [15]:
#equals
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [16]:
#greater or equal
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [17]:
#greater 
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [18]:
#less than
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [19]:
#less than or equal
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

<h2>Element-Wise Operations using functions</h2>

In [20]:
t.abs()

<function Tensor.abs>

In [21]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [22]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [23]:
t.neg().abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])