<h1>Element-Wise tensor operations for deep learning</h1>
aka: component-wise, point-wise
<h3>Rules for element-wise tensor operations (arithmetic and comparison operations)</h3>
<ul>
<li>tensors must have same shape</li>
<li>tensor and scalar operations are the exception</li>
</ul>

<h2>Arithmetic Operation</h2>
do the operation for each element (not dot or cross products)

In [2]:
#always import these two (sometimes throw matplotlib in)
import torch
import numpy as np

In [3]:
#initializing two rank 2 tensors with shape 2 x 2
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [13]:
#these work (more typing but may be easier to read)
t1.add(t2) 
t1.sub(t2)
t1.mul(t2)
t1.div(t2)

tensor([[0.1111, 0.2500],
        [0.4286, 0.6667]])

In [4]:
#addition 
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [5]:
#subtraction
t1 - t2

tensor([[-8., -6.],
        [-4., -2.]])

In [6]:
#multiplication 
#notice you just multiply each element by the other once
t1 * t2

tensor([[ 9., 16.],
        [21., 24.]])

In [7]:
#division
t1 / t2

tensor([[0.1111, 0.2500],
        [0.4286, 0.6667]])

<h3>we can do these operations with scalars just the same</h3>

In [14]:
#all the above methods work with scalars
t1.add(5) 

tensor([[6., 7.],
        [8., 9.]])

In [8]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [9]:
t1 - 2

tensor([[3., 4.],
        [5., 6.]])

In [10]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [11]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

<h3>Broadcasting</h3>
this is how the scalar-tensor operations are done
the scalar is transformed into a tensor with matching rank

In [15]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [16]:
#so adding to a scalar is really
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [17]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [18]:
t1.shape

torch.Size([2, 2])

In [19]:
t2.shape

torch.Size([2])

In [20]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [21]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])