<h1>Reduction Operations</h1>
A <i>reduction operation</i> on a tensor <b>reduces the number of elements</b> within the tensor
source: https://deeplizard.com/learn/video/K3lX3Cltt4c

In [36]:
import torch

In [37]:
#3 X 3 rank-2 tensor
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [38]:
#notice a tensor of size 1 is returned
t.sum()
#numel() : # of elements in tensor
t.sum().numel()

1

In [39]:
#confirm that the sum operation returns a tensor smaller than the input
t.sum().numel() < t.numel()


True

<h2>Common Tensor Reduction Operations</h3>
sum, product, mean, standard deviation, max

In [40]:
t.sum()

tensor(8.)

In [41]:
t.prod()


tensor(0.)

In [42]:
t.mean()

tensor(0.8889)

In [43]:
t.std()

tensor(1.1667)

In [44]:
t.max()

tensor(3.)

<h2>Reduce by Axis</h2>
reduction operations do not always reduce to single element tensor

In [45]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [46]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [47]:
#this achieves the same result as above
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [48]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

<h3>Argmax Tensor Reduction Operation</h3>
--returns the <i>index location</i> of the <b>maximum</b> value inside the calling tensor.
----the calling tensor is flattened so only one index location is needed

In [49]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [50]:
t.argmax()

tensor(11)

<h2>Accessing Elements in Tensor</h2>

In [51]:
#to get index tensor as a number
#item() only works on scalar valued tensors
t.argmax().item()

11

In [52]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [54]:
#to access a non scalar tensor
t.argmax(dim=0).tolist()

[2, 1, 1, 2]