In [17]:
#source:https://deeplizard.com/learn/video/rcc86nXKwkw
import torch
import torch.nn as nn

<h1>How Linear Layers Work</h1>
<b>input features</b> are received as a flattened 1-dimensional tensor the <b>multiplied</b> by the <b>weight matrix</b>

In [18]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)


In [19]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

In [20]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

<h2>Create PyTorch linear layer</h2>
below is a linear layer that accepts 4 in features and transforms them into 3 out features<br>
Transform from 4-dimensional space to 3-dimensional space

Transformation (linear layer operation)
y = Ax + b
<br>A: weight matrix tensor<br>
x: input tensor<br>
b: bias tensor<br>
y: Output tensor

In [21]:
#creates 4x3 weight matrix
fc = nn.Linear(in_features=4, out_features=3, bias=False)

In [22]:
#values are initialized randomly
fc(in_features)

tensor([-1.6556, -0.2219,  0.4740], grad_fn=<SqueezeBackward3>)

In [23]:
fc.weight = nn.Parameter(weight_matrix) 

In [24]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)