In [353]:
import torch
import numpy as np

Rank: number of indicies needed to access a particular element

In [354]:
a = [1,2,3,4]

In [355]:
a[2] 
#rank 1 Tensor


3

In [356]:
dd =[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [357]:
dd[0][2]
#rank 2 Tensor


3

Axis of tensor: a specific demesion of a tensor

Length of axis: how many elements are in the axis

In [358]:
dd[0]
#in a rank 2 tensor the first axis is an arrays

[1, 2, 3]

In [359]:
dd[1]

[4, 5, 6]

In [360]:
dd[0][0]
#in a rank 2 tensor the second axis is a number

1

shape: the length of each axis of the tensor

In [361]:
t = torch.tensor(dd)

In [362]:
type(t)

torch.Tensor

In [363]:
t.shape

torch.Size([3, 3])

reshaping tensor: change the shape but not elements

In [364]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [365]:
t.shape
#notice the shape is not changed

torch.Size([3, 3])

In [366]:
print(t.dtype) #tensor data 
#(there is  CPU datatype and GPU datatype)
print(t.device) #device cpu or gpu 
print(t.layout) 


torch.int64
cpu
torch.strided


tensors contain data of uniform type
computations between tensors need same dtype and device

In [367]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [368]:
t1.dtype

torch.int64

In [369]:
t2.dtype

torch.float32

pytorch uses Type Promotion now 
(low size data type will be converted to high size data type)

In [370]:
t1+t2
#returns tensor of higher dtype

tensor([2., 4., 6.])

In [371]:
t1 = torch.tensor([1,2,3])
#t2 = t1.cuda() NOTE: will only run if torch.cuda.is_available()


In [372]:
t1.device 

device(type='cpu')

In [373]:
t2.device

device(type='cpu')

In [374]:
t1 + t2
#will produce error if cuda is installed

tensor([2., 4., 6.])

<h1>Different ways to create a tensor when you have data</h1>

.Tensor: default dtype
other methods use type inference (dtype based on incomming data)

torch.Tensor() and torch.tensor() copy their input data

  torch.as_tensor() and torch.from_numpy() share their input data in memory with the original input object.

<h1>which to use?</h1>
The torch.tensor(): start with this
torch.as_tensor(): use when you want to fine tune code for performance

zero copy transfer
    -.as_tensor
    -.from_numpy()

full copy transfer
    -.Tensor()
    -.tensor()

Since numpy.ndarray objects are allocated on the CPU, the as_tensor() function must copy the data from the CPU to the GPU when a GPU is being used.

The memory sharing of as_tensor() doesn't work with built-in Python data structures like lists.

The as_tensor() call requires developer knowledge of the sharing feature. This is necessary so we don't inadvertently make an unwanted change in the underlying data without realizing the change impacts multiple objects.

The as_tensor() performance improvement will be greater if there are a lot of back and forth operations between numpy.ndarray objects and tensor objects. However, if there is just a single load operation, there shouldn't be much impact from a performance perspective.

In [375]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [376]:
torch.get_default_dtype()

torch.float32

In [377]:
torch.Tensor(data) #uses default dtype

tensor([1., 2., 3.])

In [378]:
torch.tensor(data) #prefereed over .Tensor() (more docs)
torch.tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

In [379]:
torch.as_tensor(data)
torch.as_tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

In [380]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

Different ways to make prefilled tensors

In [381]:
torch.eye(2) #returns 2d tensor with ones on the diagonal

tensor([[1., 0.],
        [0., 1.]])

In [382]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [383]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [384]:
torch.rand(2,2)

tensor([[0.1760, 0.1085],
        [0.3030, 0.2115]])

<h1>Tensor Operations</h1>
<h3>we can group tensor operations into the below</h3>
<ol>
<li>Reshaping operations</li>
<li>Element-wise operations</li>
<li>Reduction operations</li>
<li>Access operations</li>
</ol>

<h2>Reshaping operations</h2>


In [385]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [386]:
t.size()

torch.Size([3, 4])

In [387]:
t.shape #show shape of tensor

torch.Size([3, 4])

In [388]:
#see elements in tensor
torch.tensor(t.shape).prod()

tensor(12)

In [389]:
#also works
t.numel()

12

In [390]:
#many was to reshape without changing tank 
t.reshape(1,12)


tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [391]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [392]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [393]:
#increase rank to 3
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

<h1>Change shape by squeezing and unsqueezing</h1>
(removing or adding one length demensions)<br><br>
Squeezing: removes the dimensions or axes that have a length of one.<br><br>
Unsqueezing: adds a dimension with a length of one.


In [394]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [395]:
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [396]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


<h2>Flatten Tensor</h2>
flatten: remove all dimensions except one

In [397]:
def flatten(t):
    #-1 tells .reshape() to figure out the appropiate values
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t
flatten(t)

#!!!!!there is a pytorch built in flatten function!!!!!

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

<h2>concat tensors</h2>
combine tensor
dim=0 (row-wise)
dim=1 (column-wise)

In [398]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [399]:
torch.cat((t1, t2), dim=0) 

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [400]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [401]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

<h1>how images are flattened in CNNs</h1>
This example will be a grayscale image
<ul>
<li>-show how to flatten specific tensor axes</li>
<li>-work with batches of inputs</li>
</ul>

sample batch of 3 images 4x4

In [402]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

batches are represented using single tensor
combine three tensors into one three axis tensor

In [403]:
t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

a cnn will expect a color channel <br>
(in this case we will use a grayscale image)<br>
(notice how each axis is wrapped in multiple [brackets])

In [404]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [405]:
#the image
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [406]:
#the color channel
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [407]:
#the first row of pixels
t[0][0][0]

tensor([1, 1, 1, 1])

In [408]:
#first pixel value in the row of the color channel
t[0][0][0][0]

tensor(1)

some ways to flatten this batch as a whole
(we want to flatten each axis/image individually)

In [409]:
t.reshape(1,-1)[0]


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [410]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [411]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [412]:
t.flatten() #pytorch USE THIS

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

to flatten each image individual 
.flatten(start_dim=1)
honestly idk why this works just praise jah

In [413]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [414]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

<h2>Flattening an RGB image</h2>
each color channel is flattened first
flattened channels will be lined up side by side on single axis of the tensor

In [415]:
r = torch.ones(1,2,2)
g = torch.ones(1,2,2) + 1
b = torch.ones(1,2,2) + 2

img = torch.cat(
    (r,g,b)
    ,dim=0
)
img.shape


torch.Size([3, 2, 2])

In [416]:
img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [417]:
img.flatten(start_dim=0)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [418]:
img.flatten(start_dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])